version: '3'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=poll
      - POSTGRES_PASSWORD=poll
      - POSTGRES_DB=poll_db
    volumes:
      - db-data:/var/lib/postgresql/data
    command: postgres -c max_connections=200

  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db

networks:
  poll-tier:
  result-tier:
  back-tier:
    driver: bridge

volumes:
  db-data:
